primary: bin/litefs mount -config ./etc/primary.yml
krakend: echo ./etc/krakend.json | entr -nrz krakend run --config etc/krakend.json --port $PORT
secondary: bin/litefs mount -config ./etc/secondary.yml
secondary2: bin/litefs mount -config ./etc/secondary2.yml
